#!/bin/bash
while :
do
clear
echo "==================================="
echo "     Main Menu     "
echo "==================================="
echo "[1] Grant Sudo Right"
echo "[2] Revoke Sudo Right"
echo "[3] Quit"
echo -n "Enter your choice [1-3] : "
read yourch
case $yourch in
1) echo -e "Please Enter Username : "; read username; usermod -a -G wheel $username; echo "Sudo right given to $username"; read;;
2) echo -e  "Please Enter Username : "; read username; usermod  -G users $username; echo "Sudo right revoked for $username"; read;;
3) echo "Quit from script"; exit 0; read;;
4) echo "Opps!!! Please select correct choice between 1 to 3";
echo "Press a key...."; read;;

esac
done
