#!/bin/sh
#EC2_HOME=/usr/local/ec2/ec2-api-tools-1.7.5.0
export EC2_HOME=/usr/local/ec2/ec2-api-tools-1.7.5.0
export JAVA_HOME=/opt/jdk1.7.0_79
truncate -s 0 /insstart/start.txt

for instances in $(cat /insstop/instances.txt);do
echo "Starting the instance"
/usr/local/ec2/ec2-api-tools-1.7.5.0/bin/ec2-start-instances $instances -O Key_key -W Key_Key --region us-east-1
servername=$(/usr/local/ec2/ec2-api-tools-1.7.5.0/bin/ec2-describe-instances $instances -O secret_key -W acess_key --region us-east-1 |grep Name | awk '{print $5;}')
echo "Server "\"$servername\"" started successfully, Instance Id: $instances" >>/insstart/start.txt
done

/usr/sbin/sendmail -v -i -t -f mail_form  <<END
subject: Instance Start Status `date`
to: mail_to
`cat /insstart/start.txt`
END


exit
