#!/bin/bash
#
# chkconfig: 35 90 12
# description: Trac server
#
# Get function from functions library
. /etc/init.d/functions
# Start the service tarcd
start() {
        initlog -c "echo -n Starting tracd server: "

                tracd -p 8080  --basic-auth="ECOMCOE,/etc/svn-auth-users,realm" --basic-auth="COS,/etc/svn-auth-users,realm" --basic-auth="CBEE,/etc/svn-auth-users,realm" --basic-auth="TPI,/etc/svn-auth-users,realm" --basic-auth="Migration,/etc/svn-auth-users,realm" --basic-auth="plugindev,/etc/svn-auth-users,realm"   /var/www/trac-projects/ECOMCOE /var/www/trac-projects/COS var/www/trac-projects/CBEE /var/www/trac-projects/TPI /var/www/trac-projects/Migration /var/www/trac-projects/plugindev &



                ### Create the lock file ###
        touch /var/lock/subsys/tracd
        success $"tracd server startup"
        echo
}
# Restart the service tracd
stop() {
        initlog -c "echo -n Stopping tracd server: "
        killproc tracd
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/tracd
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status tracd
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
