#!/bin/bash
while :
do
clear
echo "==================================="
echo "     Main Menu     "
echo "==================================="
echo "[1] Show today's date/time"
echo "[2] Show file in current directory"
echo "[3] Show calender"
echo "[4] Start editor to write file"
echo "[5] Exit/Stop"
echo -n "Enter your choice [1-5] : "
read yourch
case $yourch in
1) echo "Today is `date`, Press a key...."; read;;
2) echo "File is in `pwd` directory, Press a key...."; read;;
3) cal; echo "Press a key....";read;;
4) vi;;
5) exit 0;;
6) echo "Opps!!! Please select correct choice between 1 to 5";
echo "Press a key...."; read;;

esac
done
